name: Build Docker Image

on:
  push

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change Directory
        run: cd ./python

      - name: Build Docker image
        run: docker build -t oldie-app-api:latest .