name: Build Docker Image

on:
  push

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[CI Skip]')"
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd python/
          docker build -t oldie-app-api:latest .
