name: Build Docker Image

on:
  push

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd python/
          git
          docker build -t oldie-app-api:latest .

      - name: Restart Container
        run: |
          docker stop oldie-app-api
          docker rm oldie-app-api
          docker run -d --name oldie-app-api -p 1234:80 oldie-app-api:latest